title: Meteor React Tutorial
subtitle: React Tutorial
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-react-tutorial
sidebar_categories:
  null:
    - index
    - changelog
  Simple Todos:
    - simple-todos/00-introduction
    - simple-todos/01-creating-app
    - simple-todos/02-collections
    - simple-todos/03-forms-and-events
    - simple-todos/04-update-and-remove
    - simple-todos/05-styles
    - simple-todos/06-hooks
    - simple-todos/07-adding-user-accounts
    - simple-todos/08-publish-and-subscribe
    - simple-todos/09-security
    - simple-todos/10-running-on-mobile
    - simple-todos/11-testing
    - simple-todos/12-next-steps
github_repo: 'meteor/react-tutorial'

url: http://react-tutorial.meteor.com/
root: /

source_dir: tutorial
content_root: tutorial

highlight:
  enable: false
