title: Meteor React Tutorial
subtitle: React Tutorial
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-react-tutorial
sidebar_categories:
  null:
    - index
    - changelog
  Simple Todos:
    - simple-todos/00-introduction
    - simple-todos/01-creating-app
github_repo: 'meteor/react-tutorial'

url: http://react-tutorial.meteor.com/
root: /

source_dir: tutorial
marked:
  breaks: false
